prometheus: 
  rbac:
    create: false

  alertmanager:
    enabled: false

  pushgateway: 
    enabled: false  

  kubeStateMetrics:
    resources:
      limits:
        cpu: 10m
        memory: 16Mi
      requests:
        cpu: 10m
        memory: 16Mi

  nodeExporter:
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 30Mi

  server:
    name: prom-server
    image: 
      tag: v1.8.1
    ingress:
      enabled: false
    replicaCount: 1
    retention: "72h"
    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      annotations: {}
      existingClaim: ""
      mountPath: /data
      size: 10Gi
      subPath: ""
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi

grafana:  
  server:
    adminUser: "change_me"
    adminPassword: "change_me"
    ingress:
      enabled: true
      name: grafana
      annotations: 
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: "true" 
        external-dns.alpha.kubernetes.io/target: change_me
      hosts: []
      tls: []
    persistentVolume:
      enabled: true
      size: 1Gi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 100Mi
    installPlugins: grafana-clock-panel,grafana-piechart-panel
    setDatasource:
      enabled: true
      restartPolicy: OnFailure
      image: appropriate/curl:latest
      activeDeadlineSeconds: 3600
      datasource:
        name: kube
        type: prometheus
        url: http://change_me.default.svc.cluster.local
        isDefault: true
        access: proxy

  serverConfigFile:
    grafana.ini: |
      [paths]
      data = /var/lib/grafana/data
      logs = /var/log/grafana
      plugins = /var/lib/grafana/plugins

      [analytics]
      reporting_enabled = false
      check_for_updates = true

      [snapshots]
      external_enabled = false

      [users]
      allow_sign_up = false
      allow_org_create = false
      auto_assign_org = false
      default_theme = dark

      [auth]
      disable_signout_menu = true

      [auth.anonymous]
      enabled = false
      
      [auth.github]
      enabled = false
      allow_sign_up = false
      
      [auth.google]
      enabled = false
      allow_sign_up = false
      
      [auth.proxy]
      enabled = true
      auto_sign_up = false
      
      [auth.basic]
      enabled = true

      [auth.ldap]
      enabled = false
      
      [smtp]
      enabled = false
      
      [log]
      mode = console
      level = info

      [event_publisher]
      enabled = false
      
      [dashboards.json]
      enabled = true
      path = /var/lib/grafana/dashboards

      [grafana_net]
      url = https://grafana.net