apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true" 
    external-dns.alpha.kubernetes.io/target: {{ .Values.app.gateway }}
spec:
  tls: 
    - secretName: {{ .Values.generic.certSecret }}
      hosts: 
        - {{ .Values.app.host }}
  rules:
  - host: {{ .Values.app.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}-svc
          servicePort: 80