apiVersion: v1
kind: Service
metadata: 
  name: {{ template "fullname" . }}-svc
spec: 
  ports: 
    - port: 80
      targetPort: {{ .Values.app.inbound }}
  selector: 
    app: {{ template "fullname" . }}