apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec: 
  replicas: {{ .Values.app.replicas }}
  template:
    metadata: 
      labels: 
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: {{ .Values.docker.image }}
        imagePullPolicy: Always
        ports: 
            - containerPort: 80
            - containerPort: 443
        args:
          - -nginx-configmaps={{ template "fullname" . }}-conf
          - -default-server-tls-secret=default/{{ .Values.generic.certSecret }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace