apiVersion: v1
kind: Service
metadata: 
  name: {{ template "fullname" . }}-svc
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.host }}

{{- if .Values.app.lbInternal }}

    service.beta.kubernetes.io/azure-load-balancer-internal: true

{{- end }}

spec: 
  type: LoadBalancer
  ports: 
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
  selector: 
    app: {{ template "fullname" . }}